name: "Eye-of-Nemesis"
version: ${version}
main: io.github.adrianvic.nemesiseye.Nemesis
author: 'Adrian Victor'
description: "Change what players can do based in custom criteria."
commands:
  eye:
    description: "Run /eye help to see all available commands."