name: "Eye-of-Nemesis"
version: ${version}
main: io.github.adrianvic.nemesiseye.Nemesis
api-version: '1.21'
author: 'Adrian Victor'
website: "https://github.io/adrianvic/NemesisEye"
description: "Change what players can do based in custom criteria."
commands:
  eye:
    usage: "/eye <option> (help for all available options)"